Use chromium that run ARM and x86_64, and use dev webdriver.
minkphp/webdriver-classic-driver pull request #29
Opened 2024-08-05 13:33 UTC by saidatom

2024-08-05 20:07 UTC, uuf6429 requested changes
Thanks for the PR! I've left a few review comments..

2024-08-05 20:07 UTC, uuf6429 commented on docker-compose.yml
> +    image: ${SELENIUM_IMAGE:-selenium/standalone-chromium:4}
The main reason `chrome` was used by default is mainly the [high market share](https://gs.statcounter.com/browser-market-share) which also means many users would expect such a browser by default (we had `firefox` before). That said, it has been defined as a variable so the user can always use a different image entirely (even a non-selenium/standalone image). Therefore I would recommend removing this change.

2024-08-06 07:08 UTC, oleg-andreyev approved these changes

2024-08-06 07:18 UTC, uuf6429 approved these changes
Pretty sure the failed tests are unrelated to these changes, so the PR looks fine IMO.
I'll look at the failures separately.

2024-08-06 07:21 UTC, merged