Fix and streamline capability handling
minkphp/webdriver-classic-driver pull request #51
Opened 2024-11-19 20:37 UTC by uuf6429

Fixes #46.

## What Changed

1. Fixes code preventing us from overwriting capbalities when they're already set by php-webdriver.
2. Streamlines the flow so that it is clearer how it behaves:
    1. start with the browser-specific capabilities provided by php-webdriver
    2. add mink default capabilities
    3. add mink browser-specific default capabilities
    4. add capabilities defined by the end user
3. 'add', in this case, always overwrites existing capabilities

## Remaining Questions

- How do we test this? (should we even test it?) In principle this is private behaviour and not something accessible from the outside.
- Should we be worried that this is a BC break? Existing users that have broken config would break their system, when in the past that config was unintentionally ignored.

2024-11-20 08:05 UTC, aik099 requested changes
> How do we test this? (should we even test it?) In principle this is private behaviour and not something accessible from the outside.

Yes. We should test, that the user can override this (no matter if it came from the `php-webdriver/php-webdriver` library or Mink itself):

* any top-level desired capability (e.g. `platform`)
* any sub-level desired capability (e.g. `goog:chromeOptions > binary`)

> Should we be worried that this is a BC break? Existing users that have broken config would break their system, when in the past that config was unintentionally ignored.

It's not a BC break.

We had similar discussions in the past about the `$name` argument of the `switchIFrame` method. According to the method's DocBlock, it should be always a string. However, we're not checking that and passing that `$name` argument directly to a WebDriver call. This allowed to have bonus undocumented behavior of switching frames by index.

When string argument typing was introduced people started complaining that this is a BC break, but it isn't because we've never advertised that passing frame index is even a supported behavior.

Same here: driver is supported to properly merge desired capabilities and the user is supposed to provide valid desired capabilities. If either of them doesn't do their work, then it's a bug and not a BC break 😄

2024-11-21 12:44 UTC, aik099 commented
Since we're not mocking the underlying WebDriver library to confirm, that proper desired capabilities were given at session creation time, then we should fall back to a functional test (like with timeouts) to indirectly confirm, that the correct desired capabilities were given.

@uuf6429 , any ideas?

2024-11-21 12:58 UTC, stof commented
thus, this driver does not have a stable release yet. So there is no BC guarantee yet.

2024-11-21 20:49 UTC, uuf6429 commented
> Since we're not mocking the underlying WebDriver library to confirm, that proper desired capabilities were given at session creation time

Why not? I can simply use an anonymous subclass to test that.

2024-11-21 21:30 UTC, uuf6429 commented
side-note: Currently there's no way to unset top-level capabilities, except with potentially wrong values (e.g. to "unset" `'name'` one would need to pass `['name' => null]` - which is more like invalidation than unsetting, and might still affect selenium).

2025-01-01 00:27 UTC, uuf6429 commented
@aik099 small reminder about this PR. I believe it's not missing anything, right?

2025-01-01 09:56 UTC, aik099 requested changes
Looks good otherwise.

2025-01-01 09:56 UTC, aik099 commented on tests/Custom/CapabilityTest.php
> +            }
Or you can just make the `getDesiredCapabilities` method public in this extended class.

2025-01-01 09:56 UTC, aik099 commented on tests/Custom/CapabilityTest.php
> +     * @param array<string, mixed> $expectedCapabilities
Is this correct behavior to specify only some of the method parameters in the PhpDoc?

2025-01-01 12:35 UTC, uuf6429 commented on tests/Custom/CapabilityTest.php
> +     * @param array<string, mixed> $expectedCapabilities
Yes - PHPDoc is to augment or narrow existing information. E.g. in this case adding a line for `string $browserName` is quite redundant (unless we want to add something special to that parameter - such as a description or `non-empty-string` instead of `string`..).

PHP-CS-Fixer even has a rule/fixer for this: [no_superfluous_phpdoc_tags](https://cs.symfony.com/doc/rules/phpdoc/no_superfluous_phpdoc_tags.html).

2025-01-01 12:41 UTC, uuf6429 commented on tests/Custom/CapabilityTest.php
> +            }
True, that should also work.. 🤔

2025-01-01 12:45 UTC, uuf6429 commented on tests/Custom/CapabilityTest.php
> +            }
Ah, I know why I did it like that - it's because in PHPStan, I cannot type hint a method on an anonymous object (see line 85).

2025-01-01 14:58 UTC, aik099 commented on tests/Custom/CapabilityTest.php
> +            }
OK.

2025-01-01 15:00 UTC, aik099 commented on tests/Custom/CapabilityTest.php
> +     * @param array<string, mixed> $expectedCapabilities
OK.

2025-01-01 15:00 UTC, aik099 approved these changes

2025-01-01 15:01 UTC, aik099 commented
To fix the tests you need to rebase.

2025-01-01 15:22 UTC, merged